chore: reduce renovate churn
LavaMoat/LavaMoat pull request #1068
Opened 2024-03-01 23:56 UTC by legobeat

This is an attempt to reduce the amount of dependency maintenance overhead from Renovate.

- Disable `minor` and `patch` for these frequently updated (>= 4 renovate PRs merged so far) devDependencies (we have other channels for security advisories):
  - `commitlint`
  - `husky`
  - `lint-staged`
  - `linters`
- Disable `major` and `patch` for `@types/node`. `major` because it should be bumped in sync with `engines.node` and `patch` because of the update-frequency, I think we're fine on only getting automation for `minor` here.

Room for improvement: I think Renovate has some functionality for consolidating configured groups of dependencies into larger update PRs. That might be a good way to keep down the merge overhead while still staying on top of new versions. Could also group all GHA actions into one such PR group, if possible.

2024-03-06 20:00 UTC, naugtur commented
LGTM but I'll wait for @boneskull

2024-03-06 21:36 UTC, boneskull reviewed
I'm not sure I like this idea.

What I _don't_ like is all the Renovate PRs for `viz`'s dependencies... which just sit.  These are clogging up the pipeline, as Renovate throttles its total count of open PRs. We should do whatever we're doing with `viz` and close those out.  

There are many levers to pull to make Renovate work better for you/us.  For example, we could change the cadence for updates to these tooling packages to once every _n_ weeks.  We could batch all tooling-related patch/minor updates together into a single PR.  We could decide upon a trusted set of tools (IMO, eslint and typescript-eslint can be trusted) we want to auto-merge.  

I just don't think disabling them entirely and requiring manual updates is the way.

2024-03-06 21:36 UTC, boneskull commented on .github/renovate.json5
> +      ],
[matchPackageNames](https://docs.renovatebot.com/configuration-options/#matchpackagenames) expects a list of _exact_ package names, so `commitlint` (not one of our direct dependencies anyhow) and `linters` should not be here.  

```suggestion
      extends: ['packages:linters'],
      matchPackagePrefixes: ['@commitlint'],
      matchPackageNames: [
        'husky',
        'lint-staged'
      ],
```

see [packages:linters](https://docs.renovatebot.com/presets-packages/#packageslinters) and [matchPackaagePrefixes](https://docs.renovatebot.com/configuration-options/#matchpackageprefixes)

2024-03-06 21:36 UTC, boneskull commented on .github/renovate.json5
> +    }
I agree on holding it back from `major` updates

2024-03-06 23:02 UTC, legobeat commented
> What I _don't_ like is all the Renovate PRs for `viz`'s dependencies... which just sit. These are clogging up the pipeline, as Renovate throttles its total count of open PRs. We should do whatever we're doing with `viz` and close those out.
> 
> There are many levers to pull to make Renovate work better for you/us. For example, we could change the cadence for updates to these tooling packages to once every _n_ weeks. We could batch all tooling-related patch/minor updates together into a single PR. We could decide upon a trusted set of tools (IMO, eslint and typescript-eslint can be trusted) we want to auto-merge.
> 
> I just don't think disabling them entirely and requiring manual updates is the way.

I don't disagree with any of that but this PR doesn't have anything to do with `viz` so somewhat unrelated to this PR? Left them out here partly to sidestep the "what to do with those packages" question from the scope of this one. Further grouping *also* sounds like a good idea.

2024-03-07 22:32 UTC, boneskull requested changes
See discussion elsewhere

2025-04-25 19:35 UTC, closed without merging