chore(core): auto-update vendored lockdown.umd.js
LavaMoat/LavaMoat pull request #1078
Opened 2024-03-06 21:58 UTC by boneskull

This changes the `lint-staged` configuration so that when `package-lock.json` is updated, the vendored `packages/core/lib/lockdown.umd.js` is copied from the currently-installed `ses` and added to the commit.

I'm not sure if this is something we want to be doing or not, but needing to run the `lib:ses` script in `lavamoat-core` after a `ses` upgrade is non-obvious for maintainers (me).

2024-03-06 22:54 UTC, legobeat requested changes

2024-03-06 22:54 UTC, legobeat commented on packages/core/package.json
> +    "lib:ses": "cp ../../node_modules/ses/dist/lockdown.umd.js ./lib/lockdown.umd.js && git add -A ./lib/lockdown.umd.js",
```suggestion
    "lib:ses": "cp ../../node_modules/ses/dist/lockdown.umd.js ./lib/lockdown.umd.js",
```
I think the package scripts like this shouldn't be modifying the local git environment, any drawback to moving it into the lint-script?

2024-03-06 22:54 UTC, legobeat commented on .config/lint-staged.config.js
> +  'package-lock.json': () => ['npm run -w lavamoat-core lib:ses'],
```suggestion
  'package-lock.json': () => ['npm run -w lavamoat-core lib:ses && git add -A ./packages/core/lib/lockdown.umd.js'],
```

2024-03-06 22:57 UTC, legobeat commented
IMO a more proper solution would be to not have a copy checked into git at all - just vendor a copy from the package `devDependency` at build-time. And maybe add it to `bundledDependencies`? 


Other than or until that, maybe giving a more helpful error message to the failing test [here](https://github.com/LavaMoat/LavaMoat/pull/772#pullrequestreview-1916341177) would also solve most of the need here, without additional magic in commit hooks?

2024-03-06 22:57 UTC, legobeat commented on .config/lint-staged.config.js
> +  'package-lock.json': () => ['npm run -w lavamoat-core lib:ses'],
I think the package scripts like this shouldn't be modifying the local git environment, any drawback to moving it into the lint-script?

2024-03-08 19:56 UTC, boneskull commented on packages/core/package.json
> +    "lib:ses": "cp ../../node_modules/ses/dist/lockdown.umd.js ./lib/lockdown.umd.js && git add -A ./lib/lockdown.umd.js",
sure (I had it this way originally but changed it for reasons that escape me)

2024-03-08 19:57 UTC, boneskull commented
Yeah, I mean, _why do we vendor `lockdown.umd.js`, anyway?_

2024-03-08 20:49 UTC, boneskull commented
Closing in lieu of a PR which removes it

2024-03-08 20:49 UTC, closed without merging