Various fixes
LavaMoat/LavaMoat pull request #117
Opened 2020-10-23 09:27 UTC by EtDu

2020-10-26 08:36 UTC, kumavis commented on packages/core/src/makePrepareRealmGlobalFromConfig.js
> +    // moduleRealmGlobal.Function = newFunction
remove plz

2020-10-26 08:36 UTC, kumavis requested changes
and fix ci

2020-10-26 08:47 UTC, EtDu commented on packages/core/src/makePrepareRealmGlobalFromConfig.js
> +    // moduleRealmGlobal.Function = newFunction
okeeee

2020-10-26 08:54 UTC, kumavis approved these changes
what could possibly 🐌

2020-10-26 08:57 UTC, merged

2021-03-09 09:23 UTC, EtDu commented
:tada: This PR is included in version lavamoat-v1.0.0 :tada:

The release is available on [GitHub release](https://github.com/LavaMoat/LavaMoat/releases/tag/lavamoat-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: