feat: @lavamoat/react-native-lockdown
LavaMoat/LavaMoat pull request #1438
Opened 2024-11-01 18:14 UTC by leotm

2025-02-18 10:12 UTC, leotm commented on packages/react-native-lockdown/src/makeGetPolyfills.js
> +  return [ses, repair, ...rnPolyfills(), ...polyfills, harden]
any polyfills before repair? (v2)

2025-02-18 10:14 UTC, leotm commented on packages/react-native-lockdown/src/repair.js
> +  legacyRegeneratorRuntimeTaming: 'unsafe-ignore'
add evalTaming unsafe and legacyHermesTaming unsafe

2025-03-24 16:03 UTC, leotm commented on packages/react-native-lockdown/src/repair.js
> +  legacyRegeneratorRuntimeTaming: 'unsafe-ignore'
- https://github.com/endojs/endo/pull/2723

2025-03-25 11:11 UTC, leotm commented on packages/react-native-lockdown/src/makeGetPolyfills.js
> +  const rnPolyfills = require('@react-native/polyfills') // TODO: require.resolve here?
no

2025-03-26 12:41 UTC, leotm commented on packages/react-native-lockdown/src/makeGetPolyfills.js
> +    const rnPolyfills = require('@react-native/polyfills')
https://github.com/facebook/react-native/blob/main/packages/react-native/rn-get-polyfills.js

`module.exports = require('@react-native/js-polyfills');`

https://github.com/facebook/react-native/tree/main/packages/polyfills

- console
- error guard

2025-03-28 17:43 UTC, leotm commented on packages/react-native-lockdown/package.json
> +  "description": "Utility for providing SES lockdown in react native apps",
```suggestion
  "description": "LavaMoat Metro plugin for providing SES lockdown in React Native apps",
```

2025-03-28 17:49 UTC, leotm commented on packages/react-native-lockdown/src/repair.js
> +  stackFiltering: 'verbose',
note: current options in metamask-mobile [patch](https://github.com/MetaMask/metamask-mobile/blob/main/patches/react-native%2B0.72.15.patch#L107-L109)

2025-03-28 17:51 UTC, leotm commented on packages/react-native-lockdown/src/repair.js
> +  evalTaming: 'unsafe-eval',
note: matching https://github.com/endojs/endo/pull/2723 once merged ([smoke](https://github.com/endojs/endo/pull/2723/files#diff-a5ee91faad1fafc221155952876cd95b9e6c1cea0b1c2e25ac325c55e1cf0adeR11))

2025-03-28 18:01 UTC, leotm commented on packages/react-native-lockdown/package.json
> +    "build": "node build.js",
remove

2025-03-28 18:03 UTC, leotm commented on packages/react-native-lockdown/src/makeGetPolyfills.js
> + * 'hermes', polyfills: ['reflect-metadata']}), }, };
extract to README.md

2025-03-28 18:07 UTC, leotm commented on packages/react-native-lockdown/src/makeGetPolyfills.js
> + * 'hermes', polyfills: ['reflect-metadata']}), }, };
<s>@lavamoat/react-native-lockdown/makeGetPolyfills</s>

@lavamoat/react-native-lockdown

makeGetPolyfills is now the `main` export

2025-03-28 18:20 UTC, leotm commented on packages/react-native-lockdown/src/makeGetPolyfills.js
> + * https://metrobundler.dev/docs/configuration/#platforms e.g. Custom React
remove, resolver option not serializer option

2025-03-28 18:27 UTC, leotm commented on packages/react-native-lockdown/src/makeGetPolyfills.js
> + * https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Core/InitializeCore.js
extract to README.md

2025-03-31 16:12 UTC, leotm commented on packages/react-native-lockdown/package.json
> +    "./src/makeGetPolyfills": "./makeGetPolyfills.js"
```suggestion
    "./repair": "./src/repair.js",
    "./harden": "./src/harden.js",
    "./makeGetPolyfills": "./src/makeGetPolyfills.js"
```

2025-03-31 16:13 UTC, leotm commented on packages/react-native-lockdown/package.json
> +    "dist",
```suggestion
    "src",
```

2025-03-31 16:44 UTC, leotm commented on packages/react-native-lockdown/package.json
> +    "ses": "1.12.0"
```suggestion
    "ses": "^1.12.0"
```

allows Hermes to init SES after https://github.com/endojs/endo/pull/2723 merged and released as ses@1.12.1 or ses@1.13.0

2025-03-31 16:47 UTC, leotm commented on packages/react-native-lockdown/src/makeGetPolyfills.js
> +    const rnPolyfills = require('@react-native/polyfills')
both almost identical
https://www.npmjs.com/package/@react-native/polyfills (stale, exports old Object.es8.js)
https://www.npmjs.com/package/@react-native/js-polyfills (latest)

2025-03-31 16:48 UTC, leotm commented on packages/react-native-lockdown/package.json
> +    "@react-native/polyfills": "2.0.0",
```suggestion
    "@react-native/js-polyfills": "^0.78.1",
```

to install and use latest RN js polyfills (which barely ever change anyway)

2025-03-31 17:11 UTC, leotm commented on packages/react-native-lockdown/README.md
> +
```suggestion
```

2025-03-31 17:12 UTC, leotm commented on packages/react-native-lockdown/README.md
> +}
```suggestion
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
const makeGetPolyfills = require('@lavamoat/react-native-lockdown');

/**
 * Metro configuration
 * https://reactnative.dev/docs/metro
 *
 * @type {import('@react-native/metro-config').MetroConfig}
 */
const config = {
  serializer: {
    getPolyfills: () =>
      makeGetPolyfills({
        engine: 'hermes',
        polyfills: [require.resolve('reflect-metadata')],
      }),
  },
};
```

2025-03-31 17:14 UTC, leotm commented on packages/react-native-lockdown/README.md
> +}
```suggestion
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
const makeGetPolyfills = require('@lavamoat/react-native-lockdown');

/**
 * Metro configuration
 * https://reactnative.dev/docs/metro
 *
 * @type {import('@react-native/metro-config').MetroConfig}
 */
const config = {
  serializer: {
    getPolyfills: () =>
      makeGetPolyfills({
        engine: 'hermes',
        polyfills: [require.resolve('reflect-metadata')],
      }),
  },
};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);
```

2025-03-31 17:32 UTC, leotm commented
how did this close :suspect:

2025-03-31 17:32 UTC, leotm commented
unsure how this closed :suspect:

2025-03-31 18:05 UTC, leotm commented on packages/react-native-lockdown/src/makeGetPolyfills.js
> +  }
```suggestion
  polyfills === undefined && (polyfills = require('@react-native/js-polyfills')());
```

2025-04-01 09:18 UTC, leotm commented on packages/react-native-lockdown/package.json
> +    "@react-native/js-polyfills": "^0.78.1",
```suggestion
    "@react-native/js-polyfills": "*",
```

to match the user's version of this pkg

2025-04-01 09:23 UTC, leotm commented on packages/react-native-lockdown/package.json
> +    "@react-native/js-polyfills": "^0.78.1",
peerDependency

2025-04-01 09:23 UTC, leotm commented on packages/react-native-lockdown/package.json
> +    "@react-native/js-polyfills": "^0.78.1",
and add as devDependency for tests

2025-04-01 18:29 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +  },
```suggestion
    }
    return config;
  },
```

2025-04-01 18:30 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +      const polyfills = config.getPolyfills()
```console
error Maximum call stack size exceeded.
RangeError: Maximum call stack size exceeded
    at config.getPolyfills (/Users/leo/Documents/GitHub/RN07215SES/node_modules/@lavamoat/react-native-lockdown/src/index.js:66:25)
    at config.getPolyfills (/Users/leo/Documents/GitHub/RN07215SES/node_modules/@lavamoat/react-native-lockdown/src/index.js:66:32)
    at config.getPolyfills (/Users/leo/Documents/GitHub/RN07215SES/node_modules/@lavamoat/react-native-lockdown/src/index.js:66:32)
    at config.getPolyfills (/Users/leo/Documents/GitHub/RN07215SES/node_modules/@lavamoat/react-native-lockdown/src/index.js:66:32)
    at config.getPolyfills (/Users/leo/Documents/GitHub/RN07215SES/node_modules/@lavamoat/react-native-lockdown/src/index.js:66:32)
    at config.getPolyfills (/Users/leo/Documents/GitHub/RN07215SES/node_modules/@lavamoat/react-native-lockdown/src/index.js:66:32)
    at config.getPolyfills (/Users/leo/Documents/GitHub/RN07215SES/node_modules/@lavamoat/react-native-lockdown/src/index.js:66:32)
    at config.getPolyfills (/Users/leo/Documents/GitHub/RN07215SES/node_modules/@lavamoat/react-native-lockdown/src/index.js:66:32)
    at config.getPolyfills (/Users/leo/Documents/GitHub/RN07215SES/node_modules/@lavamoat/react-native-lockdown/src/index.js:66:32)
    at config.getPolyfills (/Users/leo/Documents/GitHub/RN07215SES/node_modules/@lavamoat/react-native-lockdown/src/index.js:66:32)
```

2025-04-01 18:40 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +      const polyfills = config.getPolyfills()
temp fix

```suggestion
      const polyfills = require('@react-native/js-polyfills')()
```

2025-04-01 18:41 UTC, leotm commented on packages/react-native-lockdown/README.md
> +      // your previous serializer config if any
```suggestion
      // your previous serializer config if any, for example:
      // getPolyfills: () => [require.resolve('reflect-metadata')],
```

2025-04-03 13:05 UTC, leotm commented on packages/react-native-lockdown/README.md
> +It is clear Babel is preparing it to be transformed:
there's an endo issue for this somewhere

2025-04-03 13:06 UTC, leotm commented on packages/react-native-lockdown/README.md
> +## Usage
add important/tip/warning for resetting RN CLI (metro) cache upon Babel/Metro config changes, NOT relying on hot reload (or hot/cold start), to avoid rabbit holes (i.e. rebuild, native deps are cached)

2025-04-03 13:08 UTC, leotm commented on packages/react-native-lockdown/README.md
> +  // ses@1.12.0
```suggestion
  // ses@1.13.0
```

2025-04-03 13:19 UTC, leotm commented on packages/react-native-lockdown/README.md
> +It is clear Babel is preparing it to be transformed:
- https://github.com/endojs/endo/issues/662

2025-04-03 13:35 UTC, leotm commented on packages/react-native-lockdown/README.md
> +<!-- [ses-transformed-ext]: https://github.com/endojs/endo/issues/662 -->
this should work when used like `[something][ses-transformed-ext]`
strangely doesn't on `View file`, [blob](https://github.com/LavaMoat/LavaMoat/blob/671a2f0d92cdb51db6374a7ff91c4407b882bedd/packages/react-native-lockdown/ses-transformed-ext) example, [404](https://github.com/LavaMoat/LavaMoat/blob/671a2f0d92cdb51db6374a7ff91c4407b882bedd/packages/react-native-lockdown/ses-transformed-ext)

2025-04-03 16:01 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +      return [ses, repair, ...polyfills, harden]
<img width="465" alt="Screenshot 2025-04-03 at 4 47 03 pm" src="https://github.com/user-attachments/assets/980e2e6c-f7f6-4226-8a42-730ca228c6f5" />

```suggestion
      return [ses, repair, ...polyfills]
```

this is because we harden twice 1 getPolyfills 2 getRunModuleStatement
(under-the-hood `hardenIntrinsics = repairIntrinsics(options)`)

1 getPolyfills, too early

<img width="1033" alt="Screenshot 2025-04-03 at 4 53 41 pm" src="https://github.com/user-attachments/assets/0cbff4c5-7668-42c1-9e54-65514fab78af" />

2 getRunModuleStatement

<img width="1032" alt="Screenshot 2025-04-03 at 4 57 21 pm" src="https://github.com/user-attachments/assets/aedfc587-2db7-4221-a66a-8dd9a14acecc" />

2025-04-03 21:44 UTC, leotm commented on packages/react-native-lockdown/README.md
> +> An optional list of polyfills to include in the bundle. The list defaults to a set of common polyfills for Number, String, Array, Object...
and getRunModuleStatement

2025-04-07 08:56 UTC, naugtur commented on packages/react-native-lockdown/src/index.js
> +      const polyfills = require('@react-native/js-polyfills')() // TODO: respect originalConfig.getPolyfills
```suggestion
    const originalPolyfills = config.getPolyfills
    config.getPolyfills = () => {
      const polyfills = originalPolyfills()
```

react-native polyfills are used above, as a fallback for not having polyfills at all.

2025-04-07 12:15 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +      return [ses, repair, ...polyfills, harden]
create endo issue, SES_ALREADY_LOCKED_DOWN error was conceived before repair/harden

2025-04-07 14:36 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +      return [ses, repair, ...polyfills, harden]
- https://github.com/endojs/endo/issues/2760

2025-04-14 11:06 UTC, leotm commented on packages/react-native-lockdown/README.md
> +[rn-js-polyfills-error-guard-ext]: https://github.com/facebook/react-native/blob/c50f3e5f668887bfb0c7080155c066a4fdcc092c/packages/polyfills/error-guard.js#L38-L40
or
- better custom error (i.e. validatePolyfills)
- include peerDep @react-native/js-polyfills, if not included (trivial) and warn user

2025-04-14 11:37 UTC, leotm commented on packages/react-native/README.md
> +#### JSC
https://reactnative.dev/blog/2025/04/08/react-native-0.79#jsc-moving-to-community-package

2025-04-15 08:38 UTC, leotm commented on packages/react-native/README.md
> +## Troubleshooting
SES_ALREADY_LOCKED_DOWN

2025-04-15 09:04 UTC, leotm commented
react-native-lockdown (compartment later included as global)

2025-04-16 11:07 UTC, leotm commented
bug force terminating metro process (after RN CLI boots metro)
[before](https://github.com/user-attachments/assets/72b4f3ff-fa53-44be-8956-99382e591b70) `Console Warning` `Cannot connect to Metro.` `Try ...`
[after](https://github.com/user-attachments/assets/1bf27160-7206-4081-9400-ebdf2a94acf0) `Error calling RCTDeviceEventEmitter.emit` `RangeError: Maximum call stack size exceeded at [object CallSite] ...`

2025-04-17 16:43 UTC, leotm commented
createModuleIdFactory way noted in https://gist.github.com/leotm/4afbbe5d9129b155ddc82f7b53d16b96

2025-04-23 12:54 UTC, leotm commented on packages/react-native-lockdown/src/harden.js
remove file, no longer required, now called via string in metro serializer getRunModuleStatement, no longer at the end of getPolyfills as a resolvable path

2025-04-23 12:55 UTC, leotm commented on packages/react-native-lockdown/package.json
> +    "./harden": "./src/harden.js"
remove export, see https://github.com/LavaMoat/LavaMoat/pull/1438/files#r2055991252
also name was confusing with harden global

2025-04-23 13:08 UTC, leotm commented on packages/react-native-lockdown/README.md
> +  ignore: [/ses\.cjs/, /ses-hermes\.cjs/],
update babel config [ignore](https://babeljs.io/docs/options#ignore) Array<[MatchPattern](https://babeljs.io/docs/options#matchpattern)> RegExp

```suggestion
  ignore: [/\/ses\.cjs$/, /\/ses-hermes\.cjs$/],
```

verified working in https://github.com/MetaMask/metamask-mobile/pull/13771
GPT-4o failed to fix it 1st go 🤖

was ok before in minimal RN projects, but babel was ignoring ses.cjs _and ALL other .cjs files_ so overrides no longer work

2025-04-23 13:12 UTC, leotm commented on packages/react-native-lockdown/README.md
> +```
warning needed RE https://github.com/LavaMoat/LavaMoat/pull/1438#discussion_r2056017506

2025-04-23 13:24 UTC, leotm commented on packages/react-native-lockdown/README.md
> +  presets: ['module:metro-react-native-babel-preset'],
add expo preset example

2025-04-23 13:42 UTC, leotm commented on packages/react-native-lockdown/README.md
> +```
add expo example

2025-04-23 13:44 UTC, leotm commented on packages/react-native-lockdown/README.md
> +  presets: ['module:metro-react-native-babel-preset'],
update to latest
- https://github.com/facebook/react-native/blob/v0.72.17/packages/react-native/template/babel.config.js
  - module:metro-react-native-babel-preset
- https://github.com/react-native-community/template/blob/main/template/babel.config.js
  - module:@react-native/babel-preset

2025-04-23 14:05 UTC, leotm commented on packages/react-native-lockdown/README.md
> +  presets: ['module:metro-react-native-babel-preset'],
include note for old [unsupported](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) <=0.72.x users

2025-04-23 14:22 UTC, leotm commented on packages/react-native-lockdown/README.md
> +> Ensure your Babel config [ignore](https://babeljs.io/docs/options#ignore) `Array<MatchPattern>` ([MatchPattern](https://babeljs.io/docs/options#matchpattern)) `RegExp` is correct for both SES shims
clarify both are examples to avoid need for another TIP project setup may vary

2025-05-28 11:13 UTC, leotm commented on packages/react-native-lockdown/README.md
mention somewhere this is beta ver

2025-05-28 11:22 UTC, leotm commented on packages/react-native-lockdown/README.md
> +> If you're still on unsupported React Native <=0.72.x, use the old `'module:metro-react-native-babel-preset'` preset instead
```suggestion
> If you're still on [unsupported](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) React Native <=0.72.x, use the old `'module:metro-react-native-babel-preset'` preset instead
```

2025-05-28 11:50 UTC, leotm commented on packages/react-native-lockdown/README.md
well... we don't mention it in webpack readme, reflected in package.json semver instead

2025-05-28 11:51 UTC, leotm commented on packages/react-native-lockdown/package.json
> +  "version": "0.0.1",
```suggestion
  "version": "0.0.1-beta.0",
```

2025-05-28 12:08 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +  lockdownSerializer: ({ hermesRuntime = false } = {}, originalConfig) => {
default to true?

2025-05-28 12:11 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +    const previousGetRunModuleStatement =
```suggestion
    const originalGetRunModuleStatement =
```

2025-05-28 12:13 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +  lockdownSerializer: ({ hermesRuntime = false } = {}, originalConfig) => {
```suggestion
  lockdownSerializer: ({ hermesRuntime = false } = {}, userConfig) => {
```

2025-05-28 18:40 UTC, leotm commented on packages/react-native-lockdown/README.md
> +          require.resolve('reflect-metadata'),
some other package

2025-05-28 18:41 UTC, leotm commented on packages/react-native-lockdown/README.md
> +> JSC is [moving to a Community Package][jsc-moving-to-community-package] available starting with React Native 0.79
note 2, untested on [react-native-v8](https://github.com/Kudo/react-native-v8)?

2025-05-28 18:43 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +> Remember to `react-native start --reset-cache` or `react-native bundle --reset-cache` after Babel or Metro config changes to remove cached files (default: false).
```suggestion
> Remember to `react-native start --reset-cache` or `react-native bundle --reset-cache` after Babel or Metro config changes to remove cached files (_default: false_ in both CLI commands).
```

2025-05-28 18:44 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +Simply ensure Babel is configured to ignore your flavour of SES shim like in the ReadMe babel config example.
link to README babel config

2025-05-28 18:44 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +It looks like React Native is having trouble [initializing][init-core-ext] when setting up [error handling][set-up-error-handling-ext], due to the missing [error guard][rn-js-polyfills-error-guard-ex
```suggestion
It looks like React Native is having trouble [initializing][init-core-ext] the core when setting up [error handling][set-up-error-handling-ext], due to the missing [error guard][rn-js-polyfills-error-guard-ext] polyfill.
```

2025-05-28 18:45 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +Did you remember to include the React Native JS polyfills in your custom config? See ReadMe Hermes example.
link

2025-05-29 10:31 UTC, leotm commented on packages/react-native-lockdown/README.md
> +          require.resolve('reflect-metadata'),
link to https://github.com/endojs/endo/blob/master/packages/ses/docs/guide.md#using-hardened-javascript-with-vetted-shims

2025-05-29 12:44 UTC, leotm commented
looks like Node 18 CI flake https://github.com/LavaMoat/LavaMoat/actions/runs/15322204713/job/43108265270?pr=1438
rarely Node 22/20 https://github.com/LavaMoat/LavaMoat/actions/runs/15332096949/job/43141056996?pr=1438

```log
  ✔ unit › policy › generation › dynamic import call in string (427ms)
info    › Generating LavaMoat policy from /index.js… 
info    › Generating LavaMoat policy from /index.js… 
info    › Generating LavaMoat policy from /index.js… 
info    › Generating LavaMoat policy from /index.js… 
warning › Package dynamic-require contains potential SES incompatibilities at the following locations:
- /node_modules/dynamic-require/index.js:2:9 (dynamic require) 
info    › Generating LavaMoat policy from /index.js… 
info    › Generating LavaMoat policy from /index.js… 
info    › Generating LavaMoat policy from /index.js… 
info    › Generating LavaMoat policy from /entry.js… 
info    › Generating LavaMoat policy from /entry.js… 
info    › Generating LavaMoat policy from /entry.js… 
info    › Generating LavaMoat policy from /entry.js… 
info    › Generating LavaMoat policy from /entry.js… 
info    › Generating LavaMoat policy from /entry.js… 
info    › Generating LavaMoat policy from /entry.js… 
info    › Generating LavaMoat policy from /entry.js… 
info    › Generating LavaMoat policy from /entry.js… 
  ✔ unit › policy › load-compartment-map › result is deterministic
  ─

  111 tests passed
  4 known failures
  5 tests skipped
  7 tests todo
  32 tests remained pending after a timeout
npm error Lifecycle script `test:run` failed with error:
npm error code 1
npm error path /home/runner/work/LavaMoat/LavaMoat/packages/node
npm error workspace @lavamoat/node@0.2.0
npm error location /home/runner/work/LavaMoat/LavaMoat/packages/node
npm error command failed
npm error command sh -c ava
npm error Lifecycle script `test` failed with error:
npm error code 1
npm error path /home/runner/work/LavaMoat/LavaMoat/packages/node
npm error workspace @lavamoat/node@0.2.0
npm error location /home/runner/work/LavaMoat/LavaMoat/packages/node
npm error command failed
npm error command sh -c npm run test:run


> lavamoat-perf@0.0.0 test
> exit 0


> @lavamoat/preinstall-always-fail@2.1.0 test
> exit 0
```

unrelated to recent Node 20 CI flake on main

---

also macOS bit flakey again 😅 https://github.com/LavaMoat/LavaMoat/actions/runs/15324604591/job/43115846169

continue investigation from https://github.com/LavaMoat/LavaMoat/pull/1660#issue-3062972937

2025-05-29 12:49 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +Simply ensure Babel is configured to ignore your flavour of SES shim like in the ReadMe babel config example.
https://github.blog/news-insights/product-news/relative-links-in-markup-files/

2025-05-29 13:01 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +It looks like React Native is having trouble [initializing][init-core-ext] when setting up [error handling][set-up-error-handling-ext], due to the missing [error guard][rn-js-polyfills-error-guard-ex
actually fine as is

also the logic just got extracted to its own module
- https://github.com/facebook/react-native/pull/51209

2025-05-29 13:07 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +Did you remember to include the React Native JS polyfills in your custom config? See ReadMe Hermes example.
and clarify Metro not Babel config

2025-05-29 13:51 UTC, leotm commented on packages/react-native-lockdown/package.json
> +    "@react-native/metro-config": "^0.79.1"
remove `@react-native/metro-config` for now unused
consider later adding an apps/samples folder (example app)
which ava e2e prod tests can also consume like a fixture

where ava runs (and checks output)

`react-native bundle --platform ios --dev false --entry-file index.js --bundle-output main.jsbundle.js --sourcemap-output main.jsbundle.js.map`

`react-native bundle --platform android --dev false --entry-file index.js --bundle-output index.android.bundle --sourcemap-output index.android.bundle.map`

(calling metro under-the-hood)

which means `react-native` will be a devDep for ava to run RN CLI in CI

2025-05-29 13:54 UTC, leotm commented on package-lock.json
> +      },
since 1.13.0 isn't released yet

it can be built in endo repo and used via patch-package in apps
(or yarn packed then added as a dep or resolution)

2025-05-29 16:19 UTC, leotm commented on packages/react-native-lockdown/README.md
> +const { lockdownSerializer } = require('@lavamoat/react-native')
```suggestion
const { lockdownSerializer } = require('@lavamoat/react-native-lockdown')
```

2025-05-30 00:55 UTC, boneskull requested changes
I have two (3) blockers:

- Include `LICENSE` file
- The public API must be typed. This does not mean you have to ship declarations, but the types need to exist in JSDoc (including all options). This _could_ require pulling in more production dependencies (I'm hoping type-only packages). 
- Update the `exports` in `package.json` to include `package.json` (see comment)

And one _near-blocker_:

- I feel like this _really_ needs E2E tests, but I am not sure how much pain we'd assume. They could be in a separate repo.

Everything else _should not_ be considered blocking; do with it what you will.

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/README.md
> +## Install
may want to mention the peer dep on `@react-native/js-polyfills`

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/README.md
> +### Babel config
I assume Babel is a peer dep of `@react-native/js-polyfills`?

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/README.md
> +_Examples:_
```suggestion
### Babel Config Examples
```

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/README.md
> +> If you're still on [unsupported](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) React Native <= 0.72.x, stick to the old `'module:metro-react-native-babel-preset'` pres
I'd suggest a subsection for both React Native >0.72.x and newer versions using the existing example and your suggestion here (instead of just suggesting it) 😄

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/README.md
in general, might be nice to use less inline links and more references

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/README.md
> +> Ensure your Babel config [ignore](https://babeljs.io/docs/options#ignore) `Array<MatchPattern>` ([MatchPattern](https://babeljs.io/docs/options#matchpattern)) `RegExp` is correct for both SES shims
might even be a good idea to put this as a comment directly in the example(s) instead. probably harder to miss this way

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/README.md
> +Use `lockdownSerializer` for serializer config.
```suggestion
This section shows how to use `lockdownSerializer` to configure Metro for use with Hermes.
```

(or something similar)

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/README.md
also the prerequisites should be up-front. react native versions, metro versions,  etc., etc.

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/README.md
> +```js
May want to create two more sections like

```md
##### New Metro Config

##### Existing Metro Config
```

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/README.md
> +          require.resolve('vetted-shim'),
should the reader know what `vetted-shim` is?  is a dummy path more appropriate?  should the bit on L106 be _before_ this example?

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/README.md
> +Some modules depend on language features that may not be present in the underlying platform.
I can't tell if this is supposed to be its own paragraph

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/README.md
> +> @react-native/js-polyfills is a peer dependency, likely stemming from your React Native version (example):
Could instead suggest the user run `npm ls @react-native/js-polyfills` which would show what version (if any) is installed

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/README.md
> +> JSC is [moving to a Community Package][jsc-moving-to-community-package] available starting with React Native 0.79
What does this imply?

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/README.md
> +#### JSC
I don't know what JSC even is, but I suspect that the audience would, yes?

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +> Remember to `react-native start --reset-cache` or `react-native bundle --reset-cache` after Babel or Metro config changes to remove cached files (_default: false_ in both CLI commands).
```suggestion
> Always execute `react-native start --reset-cache` or `react-native bundle --reset-cache` after Babel or Metro config changes to remove cached files.
>
```

unsure if mentioning the default is useful

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +## ReferenceError: Property 'require' doesn't exist
```suggestion
## `ReferenceError: Property 'require' doesn't exist`
```

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +<img width="467" alt="Screenshot 2025-04-11 at 3 33 22 pm" src="https://github.com/user-attachments/assets/3ebbd6f3-965f-40f5-8427-9775b9c172d5" />
- This image doesn't load for me in the rich diff
- Stuff this image somewhere in e.g., `packages/react-native-lockdown/assets/`
- Use markdown
- Don't use an image at all, and instead provide a stack trace in a fenced code block

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +Simply ensure Babel is configured to ignore your flavour of SES shim like in the ReadMe Babel config [examples][readme-babel-config].
```suggestion
Assert Babel is configured to ignore your flavour of SES shim (see the [Babel config examples][readme-babel-config] above).
```

[weasel words](https://en.wikipedia.org/wiki/Weasel_word)

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +```js
I expect that whatever image/stack trace would reference one of the lines below, which should probably be highlighted with a comment (e.g., `<----- ERROR HERE`) since GitHub doesn't provide a way to highlight a specific line.

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +Simply ensure Babel is configured to ignore your flavour of SES shim like in the ReadMe Babel config [examples][readme-babel-config].
Might want to mention that after doing so they should re-run whatever needs to be re-run

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +Did you remember to include the React Native JS polyfills in your custom Metro config? See ReadMe Hermes [example][hermes-metro-config].
```suggestion
Did you remember to include the React Native JS polyfills in your custom Metro config? See the [Hermes config example][hermes-metro-config] above.
```

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +
```suggestion

## License

Copyright © 2024 Consensys, Inc. Licensed MIT

```

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/package.json
> +    "node": ">18.0.0"
```suggestion
    "node": "^18.0.0 || ^20.0.0 || ^22.0.0 || ^24.0.0"
```

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/package.json
> +    "./repair": "./src/repair.js"
```suggestion
    "./repair": "./src/repair.js",
    "./package.json": "./package.json"
```

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/package.json
> +  "types": "./types/src/types.d.ts",
It doesn't seem types actually get generated for this package.  

You'd have to create a `tsconfig.json` and then edit the _root_ `tsconfig.json` to add this workspace to its `references`

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/package.json
> +    "ses": "^1.12.0"
```suggestion
    "ses": "1.12.0"
```

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/package.json
> +    "@react-native/js-polyfills": "^0.79.1"
```suggestion
    "@react-native/js-polyfills": "0.79.2"
```

The latest is `0.79.2` as of this writing. you'll need to re-run `npm i` and update the lockfile

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +const { warn } = console
```suggestion
'use strict'

const { warn } = console
```

lol

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +const defaultGetRunModuleStatement = (moduleId) => `__r(${moduleId})`
- please document this--what's it for? what does it do? etc.
- add jsdoc types to all functions

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +  process.on('exit', () => {
- is there some sort of metro hook or event you could listen for instead?
- if not, use the `beforeExit` hook instead, as `exit` is not guaranteed to be called

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +    Object.values(deferredWarnings).forEach((message) => {
probably more straightforward to use `for..of` here. if not, dereference `values` from `Object`

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +      deferredWarnings['calledOnceOnly'] = false
```suggestion
      deferredWarnings.calledOnceOnly = false
```

I am surprised `prettier` didn't do this for you.  do me a favor and execute `npm run setup` from the lavamoat workspace root 😄

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +    }
- why aren't these deferred?
- should we throw instead? can this be easily reproduced?

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +  // lockdownSerializer
please document this method and its signature

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +  lockdownSerializer: ({ hermesRuntime = true } = {}, userConfig) => {
this implies `userConfig` may be `undefined`, which would throw an exception on L51.  if it cannot be `undefined`, then it should be the first parameter. if it can be, then assign a default value

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +        'LavaMoat: You are using getRunModuleStatement in serializer config. Lavamoat will attempt to wrap it without breaking it, but if you are doing something unusual, we might affect how it works
grammar

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +      userConfig.getRunModuleStatement ?? defaultGetRunModuleStatement
(opinion)

assign the default value `lockdownSerializer` function signature, assuming `userConfig` is optional

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +    config.getRunModuleStatement = (moduleId) => {
This seems to conflate data (config) and behavior; it should be separate. It seems like you could solve this with a properly scoped `let` variable?

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +      throw new Error('serializer.getPolyfills must be a function')
```suggestion
      throw TypeError('Invalid options: getPolyfills must be a function')
```

- `new` is not necessary when used with intrinsic `Error`s
- `serializer` doesn't seem to reference anything here

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +    config.getPolyfills = () => {
this too should probably be kept separate from the config

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +  validatePolyfills: function validatePolyfills(polyfills) {
- probably want to use `TypeError` here
- in general I'm not opposed to this sort of thing, but I'd reach for types first.  this doesn't look complicated enough to want to pull in an object validation library (e.g. `zod`)
- L103-107 needs to be moved _before_ L102 (it's performing this check every iteration)
- We flatten `polyfills` on L94 which means that the validation that's happening here is in reference to an object that the user did not actually provide. If the user provided the correct type in the first place, why would we need to flatten? Might not need to?
- the error on L114 references `polyfills` but you're checking `polyfill`, so the message is incorrect
- on L119, by definition of `path.isAbsolute()`, the second clause of the conditional should be unnecessary
- the error on L121 should probably reference an "absolute" path instead of a "resolved" one
- it might be kind of awkward for an end-user to provide absolute paths. can/should we do this ourselves? is the current working directory configurable?
- would an end-user ever want to use our new package from an ES module?  if so, might want to support URLs in addition to filepaths

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/repair.js
> +// NB: ES5
what's this?

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/repair.js
> + * polyfills before hardening (e.g. RN JS polyfills).
```suggestion
 * polyfills before hardening (e.g. RN JS polyfills).
 *
 * @packageDocumentation
```

omitting the tag means you are documenting the variable on L16

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/repair.js
> +var dumbPolyfillExposedInternals = Object.entries(Promise).filter(
if arrow callbacks are disallowed in this workspace, please create an `.eslintrc` and disable it

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/repair.js
> +  function (entry) {
can we dereference arrays? e.g., `function ([key, value]) {`

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/repair.js
> +/**
this docstring documents the line on L40

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/test/unit/lockdownSerializer.spec.js
> +  t.is(error.message, 'serializer.getPolyfills must be a function')
```suggestion
  t.throws(() => lockdownSerializer({}, originalConfig), {
    instanceOf: Error,
    message: 'serializer.getPolyfills must be a function',
  })
```

L20 is redundant

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/test/unit/lockdownSerializer.spec.js
> +// Snapshot test for lockdownSerializer
```suggestion
```

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/test/unit/validatePolyfills.spec.js
> +  )
```suggestion
  t.throws(() => validatePolyfills('not-an-array'), {
    instanceOf: Error,
    message:
      'Expected polyfills to be an array of strings, but received string',
  })
```

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/test/unit/validatePolyfills.spec.js
> +  )
```suggestion
  t.throws(() => validatePolyfills(polyfills), {
    instanceOf: Error,
    message:
      'Expected polyfills to be an array of strings, but received number',
  })
```

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/test/unit/validatePolyfills.spec.js
> +  )
```suggestion
  t.throws(() => validatePolyfills(polyfills), {
    instanceOf: Error,
    message: `Expected polyfills to be an array of strings, but found a function. Looks like you're passing react-native/js-polyfills but not calling the function they export. Yes, it's not very intuitive, but it is what it is.`,
  })
```

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/test/unit/validatePolyfills.spec.js
> +  )
```suggestion
  t.throws(() => validatePolyfills(polyfills), {
    instanceOf: Error,
    message:
      'Polyfill must be a resolved path, not just a package name: polyfill2',
  })
```

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +[hermes-metro-config]: README.md#hermes
```suggestion
[hermes-metro-config]: #hermes
```

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +[readme-babel-config]: README.md#babel-config
```suggestion
[readme-babel-config]: #babel-config
```

2025-05-30 00:55 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +      throw new Error('serializer.getPolyfills must be a function')
Also: if the user can provide their own function, is `@react-native/js-polyfills` an _optional_ peer dependency?

2025-05-30 07:47 UTC, naugtur commented on packages/react-native-lockdown/README.md
> +### Babel config
Babel is an inherent part of Metro and/or react-native. Hermes lacks a lot of standard JS features. (like async generaators or arrow functions)

2025-05-30 07:50 UTC, naugtur commented on packages/react-native-lockdown/test/unit/lockdownSerializer.spec.js
> +  t.is(typeof config.getPolyfills, 'function')
This is way too shallow. We need a test that runs each of the functions in a realistic scenario and asserts it behaved correctly.

2025-05-30 12:25 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +[readme-babel-config]: README.md#babel-config
this needs to link to the ReadME ^ since the heading's over there

2025-05-30 12:25 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +[hermes-metro-config]: README.md#hermes
https://github.com/LavaMoat/LavaMoat/pull/1438#discussion_r2115834512

2025-05-30 12:32 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +[readme-babel-config]: README.md#babel-config
@naugtur suggested splitting the growing README.md, so i added TROUBLESHOOTING.md and using [relative](https://github.com/LavaMoat/LavaMoat/pull/1438#discussion_r2113876401) links between the two

2025-05-30 12:33 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +[readme-babel-config]: README.md#babel-config
also noting now we got
- root CONTRIBUTING.md, SECURITY.md
- pkg CHANGELOG.md (gen'ed by release pls)
- browserify NOTES.md (atypical)
- pkg LICENSE.md (thx for pointing out)

2025-05-30 13:35 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +
added ^ it's only in the laverna readme atm, do we intend to add this to all pkg readme's? or all .md files?
also added the license md now... better to link to that instead?

2025-05-30 13:37 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +
oh wait... and we want 2025 😄

2025-05-30 13:44 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +<img width="467" alt="Screenshot 2025-04-11 at 3 33 22 pm" src="https://github.com/user-attachments/assets/3ebbd6f3-965f-40f5-8427-9775b9c172d5" />
> This image doesn't load for me in the rich diff

i think you and @naugtur rely too much on rich diff 😅 pls `View file` instead!

<img width="724" alt="Screenshot 2025-05-30 at 2 41 27 pm" src="https://github.com/user-attachments/assets/6d8b8a37-173f-4bda-85f9-3f9e6377a518" />

2025-05-30 13:47 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +<img width="467" alt="Screenshot 2025-04-11 at 3 33 22 pm" src="https://github.com/user-attachments/assets/3ebbd6f3-965f-40f5-8427-9775b9c172d5" />
afaik this is markdown, or it wouldn't view correctly?

2025-05-30 13:52 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +<img width="467" alt="Screenshot 2025-04-11 at 3 33 22 pm" src="https://github.com/user-attachments/assets/3ebbd6f3-965f-40f5-8427-9775b9c172d5" />
ah do you mean [no-inline-html](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md033.md)? i screenshot then drag n drop the img into GH comment, then copy pasta the result, which i see warns on this rule

2025-05-30 13:57 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +<img width="467" alt="Screenshot 2025-04-11 at 3 33 22 pm" src="https://github.com/user-attachments/assets/3ebbd6f3-965f-40f5-8427-9775b9c172d5" />
just discovered we can copy an img, paste it direct into a vscode md file

which generates `![alt text](<Screenshot 2025-05-29 at 8.32.25 pm.png>)` 🎉 no more inline html via browser

which automatically adds the img into the folder, then only need to move to `/assets` and update the relative path

2025-05-30 14:05 UTC, leotm commented on packages/react-native-lockdown/README.md
> +#### JSC
JavaScript Core ^ the default RN prod JS engine, before Hermes got introduced in RN 0.70

2025-05-30 14:07 UTC, leotm commented on packages/react-native-lockdown/README.md
> +#### JSC
thinking about it, Hermes been the [default](https://reactnative.dev/blog/2022/07/08/hermes-as-the-default) just shy of 3yrs now, nearly 10 major versions... so perhaps newer userland may not know what it is

2025-05-30 14:08 UTC, leotm commented on packages/react-native-lockdown/README.md
> +#### JSC
if a newer dev didn't know, was hoping the NOTE alert below this example would shed light which links to https://reactnative.dev/blog/2025/04/08/react-native-0.79#jsc-moving-to-community-package

2025-05-30 14:20 UTC, leotm commented on packages/react-native-lockdown/README.md
> +> JSC is [moving to a Community Package][jsc-moving-to-community-package] available starting with React Native 0.79
implies that users needing/wishing to use legacy JSC with RN 0.79+ can't just keep Hermes off in their project, since JSC's been removed from RN core (they need to now [install](https://github.com/react-native-community/javascriptcore?tab=readme-ov-file#installation) a separate opt-in pkg)

2025-05-30 14:20 UTC, leotm commented on packages/react-native-lockdown/README.md
> +> JSC is [moving to a Community Package][jsc-moving-to-community-package] available starting with React Native 0.79
so implies no change RE this config/setup ^ just a note/tip for likely a v small number of users

2025-05-30 14:29 UTC, leotm commented on packages/react-native-lockdown/LICENSE.md
> +Copyright (c) 2023 Consensys Software
```suggestion
Copyright (c) 2024 Consensys Software
```

2025-05-30 20:07 UTC, boneskull commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +[readme-babel-config]: README.md#babel-config
ah, sorry, still thought we were in `README.md`

2025-05-30 20:08 UTC, boneskull commented on packages/react-native-lockdown/LICENSE.md
> +Copyright (c) 2023 Consensys Software
- the year should be the year you started the work, not the current year
- rename to `LICENSE` since it's not markdown

2025-05-30 20:09 UTC, boneskull commented on package-lock.json
> +      },
So we need `ses@1.13.0` for this PR to pass CI, right?

2025-06-03 11:38 UTC, leotm commented on packages/react-native-lockdown/package.json
> +    "ses": "^1.12.0"
now bumped and pinned to https://github.com/endojs/endo/releases/tag/ses%401.13.0

2025-06-03 12:14 UTC, leotm commented on packages/react-native-lockdown/README.md
> +#### JSC
updated ReadMe to use term _JavaScriptCore_ and heading to _JavaScriptCore (JSC)_

2025-06-04 11:10 UTC, leotm commented on packages/react-native-lockdown/README.md
> +### Babel config
just to clarify in a [vanilla](https://github.com/react-native-community/template/tree/0.76.9/template) RN proj the user gets `@react-native/js-polyfills` from

```console
RN0769@0.0.1
├─┬ @react-native/metro-config@0.76.9
│ └── @react-native/js-polyfills@0.76.9
└─┬ react-native@0.76.9
  └── @react-native/js-polyfills@0.76.9 deduped
```

2025-06-04 11:12 UTC, leotm commented on packages/react-native-lockdown/README.md
> +### Babel config
and comes with [metro.config.js](https://github.com/react-native-community/template/blob/0.76.9/template/metro.config.js) that uses it ^ (which our pkg hooks into)

2025-06-04 11:19 UTC, leotm commented on packages/react-native-lockdown/README.md
> +### Babel config
RE Babel the metro config uses it too

```console
RN0769@0.0.1
├── @react-native/babel-preset@0.76.9
└─┬ @react-native/metro-config@0.76.9
  └─┬ @react-native/metro-babel-transformer@0.76.9
    └── @react-native/babel-preset@0.76.9 deduped
```

(and in a vanilla [babel.config.js](https://github.com/react-native-community/template/blob/0.76.9/template/babel.config.js) we just make sure its ignoring ses so babel not [transforming](https://github.com/endojs/endo/issues/662) it)

2025-06-04 11:47 UTC, leotm commented on packages/react-native-lockdown/README.md
> +> @react-native/js-polyfills is a peer dependency, likely stemming from your React Native version (example):
GH PR ext trying to create a link for some reason lol

<img width="889" alt="Screenshot 2025-06-04 at 12 45 21 pm" src="https://github.com/user-attachments/assets/599cdf86-c6b5-4bd2-96aa-a2243825d062" />

2025-06-04 11:50 UTC, leotm commented on packages/react-native-lockdown/README.md
> +> @react-native/js-polyfills is a peer dependency, likely stemming from your React Native version (example):
i think ok here since its clear and formats nicely in a GH alert

but if using more tree diagrams, will suggest just running `npm ls <dep>` in future to keep the ReadMe minimal

2025-06-04 11:57 UTC, leotm commented on packages/react-native-lockdown/README.md
> +## Install
i understand typically to mention peer deps right at the start during install of a lib ^

but i think in this case its fine below in `### Metro config` where relevant as an extra GH alert Note

since the user already has `@react-native/js-polyfills` since RN depends on it (and RN metro config)

2025-06-04 12:45 UTC, leotm commented on packages/react-native-lockdown/src/repair.js
> + * polyfills before hardening (e.g. RN JS polyfills).
note to self: this is a tsdoc [thing](https://tsdoc.org/pages/tags/packagedocumentation/)

(that typedoc can [use](https://typedoc.org/documents/Tags._packageDocumentation.html))

2025-06-04 13:13 UTC, leotm commented on packages/react-native-lockdown/src/repair.js
> +/**
updated to single line, which afaik no longer docs the final line ([example](https://github.com/endojs/endo/blob/e29b850b378bd19337d3af7a9ca44c17951e2edf/packages/ses/src/permits.js#L1722-L1724))

2025-06-04 19:51 UTC, leotm commented on packages/react-native-lockdown/src/repair.js
> +// NB: ES5
removed comment and clarified in packageDocumentation above

2025-06-04 19:54 UTC, leotm commented on packages/react-native-lockdown/src/repair.js
> +var dumbPolyfillExposedInternals = Object.entries(Promise).filter(
rewrote var to const and removed both stale eslint disables

arrow fn is only not allowed in the file, i've clarified above in packageDocumentation

2025-06-04 20:17 UTC, leotm commented on packages/react-native-lockdown/src/repair.js
> +  function (entry) {
unforts not (i've clarified above in packageDocumentation)

reason being an arrow fn or destructuring array params triggers Babel to transform

```
!(function(e){var n=Object.entries(Promise).filter((function(e){return!!e[1]&&e[0].startsWith('_')}));repairIntrinsics({errorTaming:'unsafe',consoleTaming:'unsafe',errorTrapping:'none',unhandledRejectionTrapping:'none',overrideTaming:'severe',stackFiltering:'verbose',evalTaming:'unsafe-eval'}),Object.assign(Promise,Object.fromEntries(n))})('undefined'!=typeof globalThis?globalThis:'undefined'!=typeof global?global:'undefined'!=typeof window&&window);
```

to

```
// rncli bundle
!(function(e){var n=require("@babel/runtime/helpers/slicedToArray"),r=Object.entries(Promise).filter((function(e){var r=n(e,2),i=r[0];return!!r[1]&&i.startsWith('_')}));repairIntrinsics({errorTaming:'unsafe',consoleTaming:'unsafe',errorTrapping:'none',unhandledRejectionTrapping:'none',overrideTaming:'severe',stackFiltering:'verbose',evalTaming:'unsafe-eval'}),Object.assign(Promise,Object.fromEntries(r))})('undefined'!=typeof globalThis?globalThis:'undefined'!=typeof global?global:'undefined'!=typeof window&&window);
```

or

```
// RN debug-mode runtime bundle on http://localhost:8081/index.bundle//&platform=android
runtime http://localhost:8081/index.bundle//&platform=android
!(function(e){var i=require("@babel/runtime/helpers/slicedToArray");Object.entries(Promise).filter((function(e){var n=i(e,2),o=n[0];return!!n[1]&&o.startsWith('_')}));})('undefined'!=typeof globalThis?globalThis:'undefined'!=typeof global?global:'undefined'!=typeof window&&window);
```

which breaks RN runtime (ReferenceError: Property 'require' doesn't exist)

which now also requires repair.js to be added to the RN project Babel ignore along with both SES shims

(i guess its a matter of preference)

2025-06-04 20:22 UTC, boneskull commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +
I figured 2024 was when you started on this :D

But yeah, that tagline should probably be in all the README's.

2025-06-05 10:55 UTC, leotm commented on package-lock.json
> +      },
(updated to https://github.com/endojs/endo/releases/tag/ses%401.13.0)

not this PR yes in follow-up that will introduce an [e2e test](https://github.com/LavaMoat/LavaMoat/pull/1438#discussion_r2114025119)

2025-06-05 10:58 UTC, leotm commented on packages/react-native-lockdown/package.json
> +    "@react-native/metro-config": "^0.79.1"
note: a fuller e2e test would be not only bundling but also testing example app RN runtime prod build on Android/iOS, but more expensive in CI

2025-06-05 11:51 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +      deferredWarnings['calledOnceOnly'] = false
ran `npm run setup` and `Format Document (forced)` but still no autofix 🤔 updated anyway

2025-06-05 12:06 UTC, leotm commented on packages/react-native-lockdown/README.md
> +Some modules depend on language features that may not be present in the underlying platform.
moved above now [before](https://github.com/LavaMoat/LavaMoat/pull/1438#discussion_r2114902064) the example

2025-06-05 12:07 UTC, leotm commented on packages/react-native-lockdown/README.md
> +Some modules depend on language features that may not be present in the underlying platform.
reason i didn't before was i don't want to overload the user with info before _showing some code_, but i suppose it should be read first

2025-06-05 12:10 UTC, leotm commented on packages/react-native-lockdown/README.md
> +          require.resolve('vetted-shim'),
moved the vetted shims explainer now before this example so its clear what it is
(was concerned overloading the user w info before showing the snippet)

2025-06-05 12:16 UTC, leotm commented on packages/react-native-lockdown/README.md
> +          require.resolve('vetted-shim'),
updated to dummy path with commented example

2025-06-05 12:28 UTC, leotm commented on packages/react-native-lockdown/README.md
> in general, might be nice to use less inline links and more references

updated all inline to ref links

2025-06-05 12:36 UTC, leotm commented on packages/react-native-lockdown/README.md
> also the prerequisites should be up-front. react native versions, metro versions, etc., etc.

i don't think need to be upfront since this readme covers all active, end of cycle, unsupported RN versions
https://github.com/reactwg/react-native-releases/blob/main/docs/support.md

2025-06-05 12:36 UTC, leotm commented on packages/react-native-lockdown/README.md
and specifying side-by-side metro/babel/hermes/etc versions would be overkill

2025-06-05 12:37 UTC, leotm commented on packages/react-native-lockdown/README.md
maybe we should be specifying webpack versions upfront in our readme over there tho 👀

2025-06-05 12:39 UTC, leotm commented on packages/react-native-lockdown/README.md
> +> Ensure your Babel config [ignore](https://babeljs.io/docs/options#ignore) `Array<MatchPattern>` ([MatchPattern](https://babeljs.io/docs/options#matchpattern)) `RegExp` is correct for both SES shims
will do in follow-up PR with [e2e test](https://github.com/LavaMoat/LavaMoat/pull/1438#discussion_r2114025119) and example(s)/fixture(s) that ava will run hopefully not too expensively

2025-06-05 12:46 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +Simply ensure Babel is configured to ignore your flavour of SES shim like in the ReadMe Babel config [examples][readme-babel-config].
weaseled out the weasel words lol

2025-06-05 12:48 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +Simply ensure Babel is configured to ignore your flavour of SES shim like in the ReadMe Babel config [examples][readme-babel-config].
and mentioned after to rncli with --reset-cache flag (didn't mention 'above' since its in different .md file)

2025-06-05 13:09 UTC, leotm commented on packages/react-native-lockdown/README.md
> +```js
added sections and refactored all titles

2025-06-05 13:31 UTC, leotm commented on packages/react-native-lockdown/README.md
> +> If you're still on [unsupported](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) React Native <= 0.72.x, stick to the old `'module:metro-react-native-babel-preset'` pres
done ^

2025-06-05 13:33 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +Did you remember to include the React Native JS polyfills in your custom Metro config? See ReadMe Hermes [example][hermes-metro-config].
updated ^ (without 'above', since in different .md file)

2025-06-05 16:43 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +<img width="467" alt="Screenshot 2025-04-11 at 3 33 22 pm" src="https://github.com/user-attachments/assets/3ebbd6f3-965f-40f5-8427-9775b9c172d5" />
updated, rich diff displays images now, including vscode Preview

2025-06-05 16:43 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +const defaultGetRunModuleStatement = (moduleId) => `__r(${moduleId})`
done ^

2025-06-05 17:17 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +  // lockdownSerializer
done ^

2025-06-05 17:25 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +  process.on('exit', () => {
updated ^ i wasn't able to find such hook/event, unless i missed it browsing the [docs](https://metrobundler.dev/docs/configuration)

2025-06-05 17:44 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +  process.on('exit', () => {
had to revert to `exit` in the end, otherwise the ava tests never finish

2025-06-05 17:48 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +```js
i thought it would be obvious enough to the user it's happening on the first `require`

but added the comment for clarity ^

2025-06-05 17:54 UTC, leotm commented on packages/react-native-lockdown/package.json
> +  "types": "./types/src/types.d.ts",
removed ^ noting we have this field currently in 6/17 packages

2025-06-05 18:26 UTC, leotm commented on packages/react-native-lockdown/test/unit/lockdownSerializer.spec.js
> +  t.is(typeof config.getPolyfills, 'function')
done ^

2025-06-05 18:34 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +        'LavaMoat: You are using getRunModuleStatement in serializer config. Lavamoat will attempt to wrap it without breaking it, but if you are doing something unusual, we might affect how it works
updated ^

2025-06-05 18:45 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +      throw new Error('serializer.getPolyfills must be a function')
updated ^

2025-06-05 18:49 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +      throw new Error('serializer.getPolyfills must be a function')
nope not an optional peer dependency (which would be [peerDependenciesMeta](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta) i think)

2025-06-05 18:50 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +      throw new Error('serializer.getPolyfills must be a function')
but listed in our package.json as under `peerDependencies` and mentioned in ReadMe

2025-06-06 07:40 UTC, naugtur commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +## License
I think this part is a leftover from when this content was in README. Troubleshooting docs don't need their own license ;)

2025-06-06 07:52 UTC, naugtur commented on packages/react-native-lockdown/src/index.js
> +    }
our code only gets invoked for each of the bundle entry module ids. metro bundles have (from what we managed to observe) two entries - the actual entry (id 0) and the part of react native initialization that is in the deendencies of the main entry (non-zero id, something around 60), but gets required first manually.
We expect this to be the approximate order of things.

The warnings we can report the moment we see them, we do report right away.
The warnings that are based on knowing that the process has finished and left us with an unexpected log, are deferred.

We don't throw because the software worked anyway and it's likely fine (eg. one of the mobile app builds calls our stuff twice with the same sequence of IDs and only uses the second pass. So we warn about it but not break because it was still successful)

2025-06-06 08:26 UTC, naugtur approved these changes

2025-06-06 14:28 UTC, leotm commented on packages/react-native-lockdown/TROUBLESHOOTING.md
> +## License
updated ^

2025-06-06 14:29 UTC, leotm commented on packages/react-native-lockdown/src/repair.js
> + * Called with lockdown options ideal for React Native apps.
wanted to `@link repairOptions` here
- https://github.com/endojs/endo/pull/2845

2025-06-06 22:40 UTC, boneskull approved these changes
I don't have any blockers, but some more suggestions / questions.

2025-06-06 22:40 UTC, boneskull commented on packages/react-native-lockdown/assets/Cannot-read-property-setGlobalHandler-of-undefined.png
Now that I can see the images, I don't know why they are images and not just fenced code blocks.

2025-06-06 22:40 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> + */
```suggestion
/**
 * @import {SerializerConfig} from '@react-native/metro-config'
 */
```

This is the new-ish better way to do this sort of thing

2025-06-06 22:40 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> + */
Were you planning on adding a `tsconfig.json` so that we can ship type declarations?  If not, I can send a PR to do this after.  If so, please lmk if you run into trouble (since our setup is very "composite project"-heavy)

2025-06-06 22:40 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +    }
@leotm  I think this probably deserves a comment explaining what's happening here.

2025-06-06 22:40 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> + * @returns {SerializerConfig} Configured serializer options with LavaMoat
```suggestion
 * @returns {Omit<SerializerConfig, 'getRunModuleStatement' | 'getPolyfills'> & {getRunModuleStatement: GetRunModuleStatement, getPolyfills: GetPolyfills}}
```

The return type is guaranteed to have these two properties. Since that's a mouthful, you might want to stuff it in a `@typedef` (e.g., `LockdownSerializerConfig`).

2025-06-06 22:40 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +    )
Should we also warn about `getPolyfills`?

2025-06-06 22:40 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +const validatePolyfills = (polyfills) => {
```suggestion
/**
 * Validates that required polyfills are correct.
 *
 * @param {unknown} polyfills - Array of polyfill paths
 * @returns {asserts polyfills is ReadonlyArray<string>}
 * @throws {TypeError} If required polyfills are invalid
 */
const validatePolyfills = (polyfills) => {
```

Since we're checking if the value is an array, this function _technically_ accepts an unknown value.  If the function does not throw, the return type will cause the parameter to be inferred as `ReadonlyArray<string>` thereafter:


```js
const polyfills = [] // type `never[]`
validatePolyfills(polyfills)
polyfills // type `ReadonlyArray<string>`
```

> The above example begs the question, "is an empty array valid?" which you may need to answer 😄 

As a matter of convention, I would rename the function `assertPolyfills` (but that's just me).

2025-06-06 22:40 UTC, boneskull commented on packages/react-native-lockdown/src/repair.js
> + * Called with lockdown options ideal for React Native apps.
Cross-module linking is basically broken; unless you have a reference handy, don't worry about it

2025-06-06 22:40 UTC, boneskull commented on packages/react-native-lockdown/src/repair.js
> +  function (entry) {
Can we document this in a comment somewhere?

2025-06-06 22:41 UTC, boneskull commented on packages/react-native-lockdown/src/index.js
> +const validatePolyfills = (polyfills) => {
Oh, and the variable can be named `allegedPolyfills` 😆

2025-06-09 12:05 UTC, leotm commented on packages/react-native-lockdown/assets/Cannot-read-property-setGlobalHandler-of-undefined.png
the intent was to show something v familiar to the user

2025-06-09 12:07 UTC, leotm commented on packages/react-native-lockdown/assets/Cannot-read-property-setGlobalHandler-of-undefined.png
but on 2nd thought fenced code block
- allows stripping repetition from error msg
- better for seo
- keeps this repo minimal w/o assets/images

2025-06-09 13:07 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> + */
yes after merging 🙏 for consistent TS setup/shipping in all our packages, will do

2025-06-09 13:32 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +    )
no need imo since we've added helpful validation to ensure user polyfills are compat with Metro

2025-06-09 13:47 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> + * @returns {SerializerConfig} Configured serializer options with LavaMoat
`Partial<SerializerConfig>` could also make it less mouthfully, but your suggestion is more complete

2025-06-09 15:26 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +const validatePolyfills = (polyfills) => {
makes sense RE the types ^ updated

2025-06-09 15:27 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +const validatePolyfills = (polyfills) => {
perhaps `assertPolyfills` should _really_ be `assertPolyfillsAreValidForMetro`

but i think `assertPolyfills` is fine with new updated fn JSDoc description
> Asserts the alleged polyfills are valid for serialization by Metro.

2025-06-09 16:09 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +const validatePolyfills = (polyfills) => {
it's invalid ^ if the user provides getPolyfills that returns an empty array (Metro behaviour)

but we guide the user in _ReadMe > Existing config_ (along with an example)
> If you already used a serializer configuration, you can pass it as second argument.
`lockdownSerializer` will provide the `@react-native/js-polyfills` by default, but if you specified your own `getPolyfills` function, Metro is expecting you to provide the polyfills and `lockdownSerializer` follows that behavior too.

(and in case they don't include `@react-native/js-polyfills` like Metro expects, i added _Troubleshooting > Cannot read property 'setGlobalHandler' of undefined_)

but if worth it we can extend `assertPolyfills` to check the array that `@react-native/js-polyfills` is included

2025-06-09 16:22 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +    }
added ^

2025-06-09 17:03 UTC, leotm commented on packages/react-native-lockdown/src/repair.js
> +  function (entry) {
done ^

2025-06-09 17:05 UTC, leotm commented on packages/react-native-lockdown/src/index.js
> +  lockdownSerializer: ({ hermesRuntime = true } = {}, userConfig) => {
updated to assign default value `userConfig = {}`

2025-06-09 17:15 UTC, leotm commented on packages/react-native-lockdown/LICENSE.md
> +Copyright (c) 2023 Consensys Software
i followed convention

<img width="336" alt="Screenshot 2025-06-09 at 6 12 14 pm" src="https://github.com/user-attachments/assets/5776cce4-59b4-41e9-8d77-af3e143b7327" />

why were our new packages (node, webpack, lavapack) not created file extention-less?

happy to rename them all after merging this

2025-06-09 17:16 UTC, leotm commented on packages/react-native-lockdown/LICENSE.md
> +Copyright (c) 2023 Consensys Software
laverna's missing a LICENSE, i'll add that as well after

2025-06-09 19:30 UTC, leotm commented
tested in metamask-mobile, 120 commit rebase inc

2025-06-09 20:14 UTC, boneskull approved these changes
LGTM

2025-06-09 20:15 UTC, boneskull commented
@leotm I'll let you squash this mofo

2025-06-10 11:40 UTC, leotm commented on packages/react-native-lockdown/test/unit/validatePolyfills.spec.js
rename to `assertPolyfills.spec.js` 😅

2025-06-10 12:14 UTC, leotm commented on packages/react-native-lockdown/LICENSE.md
> +Copyright (c) 2023 Consensys Software
thanks for
- https://github.com/LavaMoat/LavaMoat/pull/1700

renamed it in this PR too

2025-06-10 13:30 UTC, merged