Run automatic `node-gyp build`
LavaMoat/LavaMoat pull request #359
Opened 2022-08-07 17:02 UTC by BendingBender

As described by: https://github.com/npm/cli/blob/f9abee79abe541226a249f50bdeec41317dd5712/docs/content/configuring-npm/package-json.md#default-values

2022-12-24 03:56 UTC, legobeat commented
Hello @BendingBender - thank you for your contribution and apologies for leaving this hanging. If you are still interested in this, would you be able to reduce this to the changes needed for this feature (removing or splitting out for example the .nvmrc and .gitignore changes)?

2022-12-24 11:47 UTC, BendingBender commented
OK, I've removed all the unnecessary changes and rebased to current main.

2024-01-12 22:07 UTC, boneskull requested changes, later dismissed
@BendingBender If you're still listening, I apologize.

This is so old that the URL in the PR body no longer points to useful information, so I have no idea why we should merge this.

- [ ] needs to be rebased onto `main`
- [ ] `rimraf` can be removed; use `fs.rm`

2024-01-12 22:08 UTC, boneskull commented on packages/allow-scripts/src/index.js
> +      }
```suggestion
      try {
        await fs.stat(path.join(filePath, 'binding.gyp'))
        lifeCycleScripts.unshift('install')
        depScripts.install = 'node-gyp rebuild'
      } catch {}
```

2024-04-22 09:42 UTC, naugtur approved these changes
Sorry for hanging on to this for so long. I'll merge to a branch and address any leftover reviews internally.

2024-04-22 09:55 UTC, merged

2024-04-22 09:56 UTC, naugtur commented
@BendingBender expect it in the next release