Parse config override
LavaMoat/LavaMoat pull request #47
Opened 2020-02-25 06:52 UTC by EtDu

Ensure that the override config was typed correctly.

2020-02-25 06:58 UTC, kumavis requested changes
- break up the individual test into many test (can be in its own file iff you want)
- create a test helper fn so you can just call
- move example configs out of util and into where the test is actually happening (fine to just define them inline)
```js
testConfigParser({ ... }, 'should catch typo ...')
```

2020-02-25 07:00 UTC, kumavis commented on src/index.js
> +function parseOverrideConfig(configOverride) {
rename to `validateConfig` not "parse"

2020-02-25 07:01 UTC, kumavis commented on src/index.js
> +  if (Object.keys(configOverride)[0] !== 'resources') {
the order is not important here, but we should check that 'resources' exists

2020-02-25 07:02 UTC, kumavis commented on src/index.js
> +  Object.entries(configOverride['resources']).forEach((resource, index) => {
you can destructure here
`forEach(([packageName, packageOptions], index) => {`

2020-02-25 07:03 UTC, kumavis commented
nice, good stuff :+1: 
just some factoring and cleanup and its good to go

2020-02-25 14:13 UTC, kumavis requested changes
Nice, looking clean. Couple more nits

2020-02-25 14:13 UTC, kumavis commented on src/index.js
> +  if (!'resources' in Object.keys(configOverride)) {
`'resources' in configOverride` or `Object.keys(configOverride).includes('resources')`

2020-02-25 14:13 UTC, kumavis commented on src/index.js
> +    if (index === 0 && packageName !== '<root>') {
i dont think we need to validate the presence of `<root>`

2020-02-25 14:13 UTC, kumavis commented on src/index.js
> +    }
```js
optionsWhitelist = [...]
packageOptions.every(packageOpt => optionsWhitelist.includes(packageOpt))
```

2020-02-25 14:13 UTC, kumavis commented on src/index.js
> +        if (value !== true) {
`'write'` is a valid value for globals. it allows packages to write to `global[key]`

2020-02-25 14:13 UTC, kumavis commented on test/config.js
> +test('Bundle fails with first configOverride', async (t) => {
improve test titles
- call out what the mistake is in the test title, eg `'invalid "resources" key'`
- "config validation fails"

2020-02-25 14:13 UTC, kumavis commented on test/config.js
> +      configOverride: configOverride
```suggestion
      configOverride,
```

2020-02-28 05:03 UTC, EtDu reviewed
Solid

2020-03-02 03:53 UTC, kumavis approved these changes

2020-03-02 03:54 UTC, kumavis commented
i suspect there will be a lint error

2020-03-02 04:47 UTC, merged