core/version - 14.1.0
LavaMoat/LavaMoat pull request #576
Opened 2023-05-15 11:50 UTC by naugtur

- restrict engines.node to < 19.0.0
 - Add `WebAssembly` scuttle globalThis exceptions - this is necessary as of Node.js 18
 - Skip JSON files only for policy generation instead of limiting to js files. Current allowlist: cjs,js,mjs,ts
 - core/fix - remove console taming to that errors are logged to the console correctly
 - core: fix globalThis polyfill
 - Fix uncaught error when receiver is null in getPropertyDescriptorDeep (#463)
 - drop uneeded additionalOpts arg and migrate back into using scenario object (#471)
 - Wrap getters calling with try catch (#468)
 - Deprecate `global`,`self` as aliases for `globalThis`

2023-05-15 13:17 UTC, legobeat approved these changes

2023-05-15 14:20 UTC, legobeat requested changes
Sibling dependents need to be updated. 

EDIT: Just pushed a commit for that on this branch. Since `viz` is lagging behind, it is bumped separately in #577.

2023-05-15 14:48 UTC, legobeat commented
Not a blocker for merge but it would be neat to get #572 in with this release as well - I think the dep bumps are minor enough to not strictly need mention in the release commit message.

2023-05-16 09:11 UTC, weizman approved these changes
lgtm

2023-05-17 08:47 UTC, legobeat approved these changes

2023-05-17 10:03 UTC, merged