lift <19 nodejs restriction for pkgs not depending on core
LavaMoat/LavaMoat pull request #586
Opened 2023-05-18 01:07 UTC by legobeat

~`@lavamoat/aa` is~ Several packages are not actually affected by the issue prompting the restriction in #552, so should be lifted prior to next release of this package.

2023-05-18 09:13 UTC, leotm approved these changes

2023-05-18 09:44 UTC, leotm requested changes
after further thought, what do we think about expanding this change to include other packages?

nb: tested linting and tests on node v20 locally for aa and thanks for our pair programming call

2023-05-18 20:59 UTC, legobeat commented
Changing scope of this PR to lift all relevant packages in monorepo.

2023-05-19 07:39 UTC, naugtur commented
+1 to larger PRs covering the same/similar change across many packages

2023-05-19 07:39 UTC, naugtur approved these changes

2023-05-19 07:47 UTC, merged