FIX : #707 packge.json file updated.
LavaMoat/LavaMoat pull request #745
Opened 2023-10-25 19:16 UTC by NiteshSamuel

packge.json file is updated. setup is updated with postinstall value.

2023-10-26 19:05 UTC, boneskull requested changes
Thanks for the PR!  I added a requested change.  There are two more issues, though.

1. Remove the `allow-scripts` property from the root `package.json`.
2. Your commit message must conform to the [conventional commits](https://conventionalcommits.org) spec.  In this case, your commit message should look something like this:

    ```
    chore: do not call allow-scripts in workspace root
    
    Closes #707
    ```

2023-10-26 19:05 UTC, boneskull commented on package.json
> +    "@lavamoat/allow-scripts": "^3.0.0",
this is not necessary, because `@lavamoat/allow-scripts` is in the `packages/allow-scripts` directory.

```suggestion
```

2023-10-29 18:35 UTC, NiteshSamuel commented
Hi @boneskull, thanks for the knowledge I appreciate it.  I did what you suggested. Have a look, and thanks again.

2023-11-01 19:25 UTC, boneskull approved these changes
Thank you!

2023-11-01 19:26 UTC, boneskull commented
Note to whoever merges: squash this one

2023-11-02 20:54 UTC, merged