feat(aa): add ESM support
LavaMoat/LavaMoat pull request #808
Opened 2023-12-21 01:36 UTC by boneskull

This adds ESM support to `aa` insofar as it will inspect the AST for imports/exports.  It does not support `await import()`.

It also accepts a custom resolver, which is needed for actually resolving ESM packages, due to the inability of the `resolve` package to do so.  Adding this natively would break the custom resolver; we may need to abandon it, because `package.json` _must_ be read in order to resolve any package having an `exports` field.

2023-12-21 01:37 UTC, boneskull commented
Current dependencies on/for this PR:
* `main`
  * **PR #808** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/808?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/808?utm_source=stack-comment).

2024-01-15 08:44 UTC, naugtur commented
> @naugtur I'm not sure if the webpack plugin would find passing a custom resolver into `@lavamoat/aa` useful?

Initially, yes. I think we already experimented with it. 
But eventually it's likely gonna need to own the traversal of dependencies and therefore use aa for path->aa transform or not at all.

2024-02-06 21:01 UTC, legobeat commented on packages/aa/src/index.js
> +let performantResolve
```suggestion
/** @type {Resolver|undefined} */
let performantResolve
```
I'm guessing this global state acts as a memoization-optimization? Could we avoid making it mutable by instantiating it immediately?
```suggestion
/** @type {Resolver} */
const performantResolve = createPerformantResolve()
```

2024-02-07 00:40 UTC, boneskull commented on packages/aa/src/index.js
> +let performantResolve
yeah, seems good

2024-02-07 01:01 UTC, boneskull commented
@LavaMoat/devs - should we deprecate or remove `createPerformantResolve` from the public API?  I don't see it used anywhere.

2024-02-07 11:52 UTC, naugtur commented
> @LavaMoat/devs - should we deprecate or remove `createPerformantResolve` from the public API? I don't see it used anywhere.

It being part of the public API is not intentional. A bug. I'd not oppose hiding it in a patch release.

2024-02-07 12:45 UTC, naugtur requested changes

2024-02-07 12:45 UTC, naugtur commented on packages/aa/src/index.js
> +      resolve !== performantResolve
I'm pretty sure I don't want this feature. 

If someone's supplying a specific resolver, they should be limited to that resolver's knowledge. Us finding the module would likely be invalid anyway.

2024-02-07 12:55 UTC, naugtur commented
Dirty check in tests is failing on a missing policy update for the switch to `node:` prefixed package names.

2024-02-07 21:33 UTC, boneskull commented on packages/aa/src/index.js
> +      resolve !== performantResolve
let me make sure I'm not actually relying on this behavior...

2024-02-07 21:48 UTC, boneskull commented
@naugtur I've removed the misfeature and updated the policy file

2024-02-07 23:04 UTC, naugtur commented on packages/aa/src/index.js
> -    if (!(/** @type {Error} */ (err).message.includes('Cannot find module'))) {
I think we were silencing the module not found errors to handle that more gracefully elsewhere.

2024-02-07 23:05 UTC, naugtur approved these changes

2024-02-08 08:43 UTC, legobeat commented on packages/aa/src/index.js
> -    if (!(/** @type {Error} */ (err).message.includes('Cannot find module'))) {
I guess this would also be more robust using `message.startsWith` as opposed to `message.includes`.

2024-02-08 21:10 UTC, naugtur approved these changes

2024-02-08 22:14 UTC, boneskull commented
needs policy file update.  going to open a PR for a solution to avoid this before hitting CI

2024-02-09 12:55 UTC, merged